spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/jwt-security-db"
    username: ""
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update